# Generated by Django 2.2.28 on 2023-08-02 10:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='P2Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg46', models.BigIntegerField()),
                ('regre46p2a', models.CharField(blank=True, max_length=20, null=True)),
                ('rel_user_n_n', models.ManyToManyField(blank=True, related_name='p2test_rel_user_n_n', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
